# Generated by Django 2.1.4 on 2019-07-03 19:05

from django.db import migrations

def create_dummy_activities(apps, schema_editor):
    activities = apps.get_model('todoapi', 'activities')

    activities(name= 'Swimming', description= 'Swim', tag= 'Outdoor, active, refreshing, watersport, cheap' ).save()
    activities(name= 'Kiteboarding', description= 'Kiteboarding', tag= 'Outdoor, active, expensive, watersport').save()
    activities(name= 'Reading', description= 'Read a book', tag= 'Both, cheap, thoughtful, creative, informative').save()


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_activities),
    ]
