# Generated by Django 2.1.4 on 2019-07-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0002_dummy_tasks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activities',
            table='activities',
        ),
    ]
